default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: <%= `docker-machine ip default`.strip %>

development:
  <<: *default
  database: friendfitter_development

test:
  <<: *default
  database: friendfitter_test
